version: '1'

services:
  employee-managment-challenge:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./ :/user/app
    container_name: EmployeeManagment
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev